book_rs/RecommendSystem/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views, api_views

# В данном случае router нужен для того, чтобы автоматизировать процесс
# создания маршрутов для вызова методов зарегистрированных представлений.
#
# Например, при использовании класса DefaultRouter роутер создает
# три группы маршрутов для каждого зарегистрированного представления:
#   1) api/v1/<прейикс> - для получения списка записей и добавления новой
#   2) api/v1/<префикс>/pk - для получения/удаления/изменения конкретной записи
#   3) api/v1/ - для получения всех имеющихся в роутере маршрутов

router = routers.DefaultRouter()
router.register(r"books", api_views.BooksViewSet)
router.register(r"genres", api_views.GenresViewSet)
router.register(r"authors", api_views.AuthorsViewSet)
router.register(r"comments", api_views.CommentsViewSet)

app_name = "RS"
urlpatterns = [
    path("", views.index, name="index"),
    path("all_books/<int:page_no>/", views.show_all_books, name="show_all_books"),
    path("one_book/<int:book_id>/", views.show_one_book, name="show_one_book"),
    path("all_authors/<int:page_no>/", views.show_all_authors, name="show_all_authors"),
    path("one_author/<int:author_id>/", views.show_one_author, name="show_one_author"),
    path("serach_books/<int:page_no>/", views.search_books, name="search_books"),
    path("serach_authors/<int:page_no>/", views.search_authors, name="search_authors"),
    path("favorite/<int:page_no>/", views.show_favorites_of_user, name="favorite"),
    path("add_favorite/<int:book_id>/", views.add_favorite, name="add_favorite"),
    path(
        "delete_favorite/<int:book_id>/", views.delete_favorite, name="delete_favorite"
    ),
    path("black_list/<int:page_no>/", views.show_black_list, name="black_list"),
    path("add_black_list/<int:book_id>/", views.add_black_list, name="add_black_list"),
    path(
        "delete_black_list/<int:book_id>/",
        views.delete_black_list,
        name="delete_black_list",
    ),
    path("add_comment/<int:book_id>/", views.add_comment, name="add_comment"),
    path(
        "delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"
    ),
    path(
        "books_of_author/<int:author_id>/<int:page_no>",
        views.show_author_books,
        name="books_of_author",
    ),
    path("like/<int:book_id>/", views.add_like, name="like"),
    path("dislike/<int:book_id>/", views.add_dislike, name="dislike"),
    path("api/v1/", include(router.urls)),
    path("api/v1/export", api_views.export_from_admin, name="export_from_admin"),
]

handler404 = "RecommendSystem.views.error_404"

book_rs/book_rs/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

SchemaView = get_schema_view(
 openapi.Info(
 title="Snippets API",
 default_version='v1',
 description="Test description",
 terms_of_service="https://www.google.com/policies/terms/",
 contact=openapi.Contact(email="contact@snippets.local"),
 license=openapi.License(name="BSD License"),
 ),
 public=True,
 permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("RecommendSystem.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path('swagger/', SchemaView.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('', include('social_django.urls')),
]

book_rs/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.RegisterView.as_view(), name="register"),
]

book_rs/RecommendSystem/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

from .models import User


class UserLoginForm(AuthenticationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Введите вашу почту",
            }
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Введите ваш пароль",
            }
        )
    )

    class Meta:
        model = User
        fields = ("email", "password")

book_rs/RecommendSystem/views.py
from django.shortcuts import render
from django.shortcuts import (
    HttpResponse,
    get_object_or_404,
    HttpResponsePermanentRedirect,
)
from .models import *
from math import ceil
from django.contrib import auth
from django.urls import reverse


# Вспомогательные функции
def get_context_for_pagination(arr: list, page_no: int, cards_count: int):
    maybe_pages = ceil(len(arr) / cards_count)
    page_no = max(1, page_no)
    page_no = min(maybe_pages, page_no)
    next_page = page_no if page_no + 1 > maybe_pages else page_no + 1
    prev_page = page_no if page_no - 1 < 1 else page_no - 1

    context = {
        "page_no": page_no,
        "maybe_pages": maybe_pages,
        "next_page": next_page,
        "prev_page": prev_page,
        "all_objects": len(arr),
        "objects_list": arr[cards_count * (page_no - 1) : cards_count * page_no],
    }

    return context


# Функции представлений
def index(request):
    """Главная страница"""
    return render(request, "index.html")


def show_all_books(request, page_no=1):
    """Просмтор всех имеющихся в БД книг"""
    user = request.user

    books_list = list(Book.objects.all())
    if user.is_authenticated:
        books_list = [book for book in books_list if not book.in_black_list(user.id)]
    context = get_context_for_pagination(books_list, page_no, 12)
    context["cur_url"] = "RS:show_all_books"
    context["h1_title"] = "Список всех книг"

    return render(request, "show_all_books.html", context)


def show_one_book(request, book_id: int):
    """Просмотр профиля отдельной книги"""
    user = request.user
    book = get_object_or_404(Book, pk=book_id)
    comments = Comment.objects.filter(book_id=book.id)
    is_favorite = False
    in_black_list = False
    is_liked = False
    is_disliked = False

    if user.is_authenticated:
        is_favorite = book.in_favorite(user.id)
        in_black_list = book.in_black_list(user.id)
        is_liked = book.was_liked(user.id)
        is_disliked = book.was_disliked(user.id)

    context = {
        "book": book,
        "comments": comments,
        "is_favorite": is_favorite,
        "in_black_list": in_black_list,
        "is_liked": is_liked,
        "is_disliked": is_disliked,
    }

    return render(request, "show_one_book.html", context)


def show_all_authors(request, page_no=1):
    """Просмотр всех авторов, имеющихся в БД"""
    authors_list = list(Author.objects.all())
    context = get_context_for_pagination(authors_list, page_no, 16)
    context["cur_url"] = "RS:show_all_authors"

    return render(request, "show_all_authors.html", context)


def show_one_author(request, author_id: int):
    """Просмотр профиля отдельного автора"""
    author = get_object_or_404(Author, pk=author_id)

    return render(request, "show_one_author.html", {"author": author})


def search_books(request, page_no: int):
    """Просмотр страницы с найденными по запросу книгами"""
    text = request.GET.get("text")
    books = list(Book.objects.filter(book_name__iregex=text))
    context = get_context_for_pagination(books, page_no, 15)
    context["cur_url"] = "RS:search_books"
    context["search_text"] = text
    context["h1_title"] = "Книги по запросу"

    return render(request, "show_all_books.html", context)


def search_authors(request, page_no: int):
    """Просмотр страницы с найденными по запросу книгами"""
    text = request.GET.get("text")
    authors = list(
        Author.objects.filter(firstname__iregex=text)
        | Author.objects.filter(lastname__iregex=text)
        | Author.objects.filter(patronymic__iregex=text)
    )
    context = get_context_for_pagination(authors, page_no, 16)
    context["cur_url"] = "RS:search_authors"
    context["search_text"] = text

    return render(request, "show_all_authors.html", context)


def show_favorites_of_user(request, page_no: int):
    user = request.user
    if user.is_authenticated:
        favotites = list(Favorite.objects.filter(user_id=user.id))
        books_list = [record.get_book() for record in favotites]
        context = get_context_for_pagination(books_list, page_no, 9)
        context["cur_url"] = "RS:favorite"
        context["h1_title"] = "Ваше любимое"

        return render(request, "show_all_books.html", context)
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def add_favorite(request, book_id: int):
    user = request.user
    book = get_object_or_404(Book, pk=book_id)
    if user.is_authenticated and book:
        new_record = Favorite()
        new_record.user_id = user.id
        new_record.book_id = book_id
        new_record.save()
        if book.in_black_list(user.id):
            HttpResponsePermanentRedirect(
                reverse("RS:delete_black_list", kwargs={"book_id": book.id})
            )
        return HttpResponsePermanentRedirect(
            reverse("RS:favorite", kwargs={"page_no": 1})
        )
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def delete_favorite(request, book_id: int):
    user = request.user
    favorite = get_object_or_404(Favorite, user_id=user.id, book_id=book_id)

    if user.is_authenticated:
        favorite.delete()
        return HttpResponsePermanentRedirect(
            reverse("RS:favorite", kwargs={"page_no": 1})
        )
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def show_black_list(request, page_no: int):
    user = request.user
    if user.is_authenticated:
        records = list(BlackList.objects.filter(user_id=user.id))
        books_list = [record.get_book() for record in records]
        context = get_context_for_pagination(books_list, page_no, 9)
        context["cur_url"] = "RS:black_list"
        context["h1_title"] = "Ваш черный список"

        return render(request, "show_all_books.html", context)
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def add_black_list(request, book_id: int):
    user = request.user
    book = get_object_or_404(Book, pk=book_id)
    if user.is_authenticated and book:
        new_record = BlackList()
        new_record.user_id = user.id
        new_record.book_id = book_id
        new_record.save()
        if book.in_favorite(user.id):
            HttpResponsePermanentRedirect(
                reverse("RS:delete_favorite", kwargs={"book_id": book.id})
            )
        return HttpResponsePermanentRedirect(
            reverse("RS:black_list", kwargs={"page_no": 1})
        )
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def delete_black_list(request, book_id: int):
    user = request.user
    record = get_object_or_404(BlackList, user_id=user.id, book_id=book_id)

    if user.is_authenticated:
        record.delete()
        return HttpResponsePermanentRedirect(
            reverse("RS:black_list", kwargs={"page_no": 1})
        )
    else:
        return render(
            request,
            "error.html",
            {
                "error_title": "Ошибка доступа",
                "error_text": "Вы не можете получить доступ к этому ресурсу так как не прошли авторизацию",
            },
        )


def add_comment(request, book_id: int):
    if request.method == "POST":
        user = request.user
        if user.is_authenticated and get_object_or_404(Book, pk=book_id):
            comment = Comment()
            comment.book_id = book_id
            comment.author_id = user.id
            comment.text = request.POST.get("comment-text")
            comment.save()
            return HttpResponsePermanentRedirect(
                reverse("RS:show_one_book", kwargs={"book_id": book_id})
            )
        else:
            return render(
                request,
                "error.html",
                {
                    "error_title": "Ошибка добавления",
                    "error_text": "Не удалось добавить комментарий",
                },
            )


def delete_comment(request, comment_id: int):
    comment = get_object_or_404(Comment, pk=comment_id)
    book_id = comment.book_id
    user = request.user

    if user.is_authenticated and comment.author_id == user.id:
        comment.delete()
        return HttpResponsePermanentRedirect(
            reverse("RS:show_one_book", kwargs={"book_id": book_id})
        )
    return render(
        request,
        "error.html",
        {
            "error_title": "Ошибка удаления",
            "error_text": "Вы не можете удалить комментарий другого человека",
        },
    )


def show_author_books(request, author_id, page_no):
    user = request.user
    author = get_object_or_404(Author, pk=author_id)
    books_list = Book.objects.filter(author_id=author_id)

    if user.is_authenticated:
        books_list = [book for book in books_list if not book.in_black_list(user.id)]
    context = get_context_for_pagination(books_list, page_no, 3)
    context["cur_url"] = "RS:books_of_author"
    context["h1_title"] = f"{author} - книги"

book_rs/RecommendSystem/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block document_title %}Базовая{% endblock document_title %}</title>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block additional_styles %}{% endblock additional_styles %}
</head>

<body>
    <header class="header">
        <div class="container header__container">
            <a href="/" class="header__logo">BRS</a>
            <nav class="header__nav">
                <ul class="menu">
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'RS:show_all_books' 1 %}">Книги</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'RS:show_all_authors' 1 %}">Авторы</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'RS:favorite' 1 %}">Любимое</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'RS:black_list' 1 %}">Черный список</a>
                    </li>
                    {% endif %}
                    <li class="menu__item">
                        <a class="menu__link" href="/api/v1">API</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="/admin">Админка</a>
                    </li>
                </ul>
                <ul class="menu header__user-info">
                    {% if not user.is_authenticated %}
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="{% url 'users:login' %}">Вход</a>
                    </li>
                    {% else %}
                    <li class="menu__item">
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button class="menu__link" type="submit">{{ user }}</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main class="container wrapper main">
        {% block content %}{% endblock content %}
    </main>
    <footer class="footer">
        <div class="container footer__container">
            <p class="common-text common-text--size_big">Переверзев Иван Дмитриевич - 221-321</p>
        </div>
    </footer>
</body>

</html>

book_rs/RecommendSystem/templates/error.html
{% extends "base.html" %}
{% block document_title %}Ошибка{% endblock document_title %}
{% block additional_styles %}{% endblock additional_styles %}
{% block content %}
    <h1>{{ error_title }}</h1>
    <hr>
    <p>{{ error_text }}</p>
{% endblock content %}

book_rs/RecommendSystem/templates/index.html
{% extends "base.html" %}
{% block document_title %}Главная{% endblock document_title %}
{% block additional_styles %}{% endblock additional_styles %}
{% block content %}
    <h1>Рекомендательная система книг</h1>
    <hr>
    <p>Добро пожаловать в книжную рекомендательную систему!</p>
{% endblock content %}

book_rs/RecommendSystem/templates/show_all_authors.html
{% extends "base.html" %}
{% block document_title %}Авторы{% endblock document_title %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/view_of_set.css' %}">
{% endblock additional_styles %}

{% block content %}
    {% load static %}

    <h1>Список всех авторов</h1>
    <hr>
    <div class="infoblock">
        <h2>Количество авторов: {{ all_objects }}</h2>
        <form action="{% url 'RS:search_authors' 1 %}">
            <input type="text" placeholder="Введите ФИО автора" name="text">
            <button class="btn">Найти</button>
        </form>
    </div>
    <hr>
    <div class="pagination">
        <a href="{% url cur_url prev_page %}{% if cur_url == 'RS:search_authors' %}?text={{ search_text }}{% endif %}" class="btn"><--</a>
        <p>{{ page_no }} / {{ maybe_pages }}</p>
        <a href="{% url cur_url next_page %}{% if cur_url == 'RS:search_authors' %}?text={{ search_text }}{% endif %}" class="btn">--></a>
    </div>
    {% if objects_list %}
        <ul class="list">
            {% for author in objects_list %}
                <li class="card">
                    <a href="{% url 'RS:show_one_author' author.id %}">
                        <img src="{% static author.image %}" alt="{{ author.lastname }} {{ author.firstname }}" class="card__img">
                        <div class="card__description">
                        <p class="common-text card__link">{{ author }}</p>
                    </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Простите, авторы не найдены :(</p>
    {% endif %}
{% endblock content %}

book_rs/RecommendSystem/templates/show_all_books.html
{% extends "base.html" %}
{% block document_title %}Книги{% endblock document_title %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/view_of_set.css' %}">

    <style>
        .list {
            grid-template-columns: repeat(3, 1fr);
        }

        .card a {
            flex-direction: row;
            align-items: start;
            text-align: start;
        }
        .card__img {
            width: 30%;
        }
    </style>
{% endblock additional_styles %}

{% block content %}
    {% load static %}

    <h1>{{ h1_title }}</h1>
    <hr>
    <div class="infoblock">
        <h2>Количество книг: {{ all_objects }}</h2>
        <form action="{% url 'RS:search_books' 1 %}">
            <input type="text" placeholder="Введите название книги" name="text">
            <button class="btn">Найти</button>
        </form>
    </div>
    <hr>
    <div class="pagination">
        <a href="
            {% if cur_url == 'RS:books_of_author' %}
                {% url cur_url author_id prev_page %}
            {% else %}
                {% url cur_url prev_page %}{% endif %}{% if cur_url == 'RS:search_books' %}?text={{ search_text }}{% endif %}" class="btn">
            Назад
        </a>
        <p>{{ page_no }} / {{ maybe_pages }}</p>
        <a href="
            {% if cur_url == 'RS:books_of_author' %}
                {% url cur_url author_id next_page %}
            {% else %}
                {% url cur_url next_page %}{% endif %}{% if cur_url == 'RS:search_books' %}?text={{ search_text }}{% endif %}" class="btn">
            Назад
        </a>
    </div>
    {% if objects_list %}
        <ul class="list">
        {% for book in objects_list %}
            <li class="card">
                <a href="{% url 'RS:show_one_book' book.id %}">
                    <img src="{% static book.image %}" alt="{{ book.book_name }}" class="card__img">
                    <div class="card__description">
                    <p class="common-text">{{ book.get_author }}</p>
                    <p class="common-text card__link">{{ book.book_name }}</p>
                    <p class="common-text">Рейтинг: {{ book.rating }}</p>
                </div>
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Простите, книги не найдены :(</p>
    {% endif %}
{% endblock content %}

book_rs/RecommendSystem/templates/show_one_author.html
{% extends "base.html" %}
{% block document_title %}{{ author }}{% endblock document_title %}

{% block additional_styles %}
    <style>
        .description {
            margin-top: 30px;
            display: flex;
            gap: 25px;
            height: 80%;
        }
        .description__info {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }
        .description__block {
            display: flex;
            flex-direction: column;
            gap: 5px;
            border-radius: 5px;
        }
        .description__img {
            height: 100%;
            width: 40%;
            display: inline-block;
            border-radius: 5px;
            object-fit: cover;
        }
    </style>
{% endblock additional_styles %}

{% block content %}
    {% load static %}

    <h1>{{ author }}</h1>
    <div class="description">
        <img class="description__img" src="{% static author.image %}" alt="">
        <div class="description__info">
            <div class="description__annotation description__block">
                <h2>Об авторе</h2>
                <p class="common-text">{{ author.description }}</p>
            </div>
            <a href="{% url 'RS:books_of_author' author.id 1 %}" class="btn">Посмотреть все работы автора</a>
        </div>
    </div>
{% endblock content %}

book_rs/RecommendSystem/templates/show_one_book.html
{% extends "base.html" %}
{% block document_title %}{{ book.book_name }}{% endblock document_title %}

{% block additional_styles %}
    <style>
        .description {
            margin-top: 30px;
            display: flex;
            gap: 25px;
        }
        .description__info {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }
        .description__block {
            display: flex;
            flex-direction: column;
            gap: 5px;
            border-radius: 5px;
        }
        .description__img {
            width: 100%;
            max-width: 30%;
            align-self: flex-start;
            display: inline-block;
            border-radius: 5px;
        }

        .button-box {
            display: flex;
            flex-direction: column;
            align-items: start;
            gap: 5px;
        }

        .vertical-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding-top: 10px;
        }

        .comment-container {
            gap: 10px;
            width: 80%;
            align-self: center;
            margin-top: 50px;

        }

        .comment {
            padding: 10px;
            gap: 10px;
            border-radius: 5px;
            border: 1px solid black;
        }
        .comment__author {
            font-weight: bold;
        }

        .form {
            max-width: 100%;
            transition: all 0.3s;
            margin-bottom: 10px;
        }

        .form-block--hidden {
            animation: form-hide 0.3s forwards;
        }
        .form-block--active {
            animation: form-show 0.3s;
        }

        @keyframes form-hide {
            from {
                opacity: 1;
                height: 100%;
            }
            to {
                opacity: 0;
                height: 0%;
            }
        }

        @keyframes form-show {
            from {
                opacity: 0;
                height: 0%;
            }
            to {
                opacity: 1;
                height: 100%;
            }
        }
        
    </style>
{% endblock additional_styles %}

{% block content %}
    {% load static %}

    <h1>{{ book.book_name }}</h1>
    <hr>
    <div class="description">
        <img class="description__img" src="{% static book.image %}" alt="">
        <div class="description__info">
            <div class="description__text description__block">
                <h2>Описание</h2>
                <p class="common-text">Автор - <a style="text-decoration: underline;" href="{% url 'RS:show_one_author' book.author_id %}">{{ book.author }}</a></p>
                <p class="common-text">Жанр: {{ book.genre }}</p>
                <p class="common-text">Год написания: {{book.year}}</p>
                <p class="common-text">Рейтинг: {{ book.rating }}</p>
            </div>
            <div class="button-box">
                {% if user.is_authenticated %}
                    {% if not is_disliked %}
                        {% if not is_liked %}
                            <a href="{% url 'RS:like' book.id %}" class="btn">Поставить лайк</a>
                        {% else %}
                            <a href="{% url 'RS:like' book.id %}" class="btn">Убрать лайк</a>
                        {% endif %}
                    {% endif %}
                    {% if not is_liked %}
                        {% if not is_disliked %}
                            <a href="{% url 'RS:dislike' book.id %}" class="btn">Поставить дизлайк</a>
                        {% else %}
                            <a href="{% url 'RS:dislike' book.id %}" class="btn">Убрать дизлайк</a>
                        {% endif %}
                    {% endif %}
                    {% if not in_black_list %}
                        {% if not is_favorite %}
                            <a href="{% url 'RS:add_favorite' book.id %}" class="btn">Добавить в любимое</a>
                        {% else %}
                            <a href="{% url 'RS:delete_favorite' book.id %}" class="btn">Удалить из любимого</a>
                        {% endif %}
                    {% endif %}
                        {% if not is_favorite %}
                        {% if not in_black_list %}
                            <a href="{% url 'RS:add_black_list' book.id %}" class="btn">Добавить в черный список</a>
                        {% else %}
                            <a href="{% url 'RS:delete_black_list' book.id %}" class="btn">Удалить из черного списка</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
            <div class="description__annotation description__block">
                <h2>Аннотация</h2>
                <p class="common-text">{{ book.annotation }}</p>
            </div>
        </div>
    </div>
    <div class="comment-container wrapper">
        <div class="vertical-wrapper">
            <h2>Комментарии</h2>
            {% if user.is_authenticated %}
            <button class="btn" id="open-form">Оставить отзыв</button>
            {% endif %}
        </div>
        <hr>
        {% if user.is_authenticated %}
        <div class="form-block form-block--hidden">
            <form action="{% url 'RS:add_comment' book.id %}" class="form" method="post" style="margin-top: 0;">
                {% csrf_token %}
                <label class="common-text" for="comment-text">Введите текст</label>
                <textarea name="comment-text" id="comment-text" cols="30" rows="10"></textarea>
                <button class="btn" type="submit" style="align-self: flex-end;">Отправить</button>
            </form>
            <hr>
        </div>
        {% endif %}
        {% if comments %}
            {% for comment in comments%}
                <div class="comment wrapper" id="comment-{{comment.id}}">
                    <p class="common-text comment__author">{{ comment.author }}</p>
                    <p class="common-text comment__text">{{ comment.text }}</p>
                    <div class="vertical-wrapper" style="border-top: 1px solid black; margin-top: 15px;">
                        {% if user.is_authenticated and user.id == comment.author_id %}
                            <div class="button-box">
                                <a href="{% url 'RS:delete_comment' comment.id %}" class="btn">Удалить</a>
                            </div>
                        {% endif %}
                        <p class="comment_date">{{ comment.created_at }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="common-text" style="text-align: center;">Комментарии к данной книге отсутствуют. Станьте первым!</p>
        {% endif %}
    </div>

    <script>
        formBlock = document.querySelector('.form-block')
        openFormBtn = document.getElementById('open-form')

        openFormBtn.addEventListener('click', () => {
            formBlock.classList.toggle('form-block--hidden')
            formBlock.classList.toggle('form-block--active')
        })
    </script>
{% endblock content %}

book_rs/RecommendSystem/templates/user_profile.html
{% extends "base.html" %}
{% block document_title %}{{ user }}{% endblock document_title %}
{% block content %}
    <h1>{{ user }}</h1>
{% endblock content %}